// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

/**
 * This package contains the implementation classes for MyAPI.
 */
package com.jesdin.taskmanager.mytaskapi.implementation;
