/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.jesdin.taskmanager.mytaskapi.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The MyTask model.
 */
public class MyTask {
    /**
     * The id property.
     */
    @JsonProperty(value = "id")
    private Integer id;

    /**
     * The title property.
     */
    @JsonProperty(value = "title")
    private String title;

    /**
     * The description property.
     */
    @JsonProperty(value = "description")
    private String description;

    /**
     * The isCompleted property.
     */
    @JsonProperty(value = "isCompleted")
    private Boolean isCompleted;

    /**
     * The isHighPriority property.
     */
    @JsonProperty(value = "isHighPriority")
    private Boolean isHighPriority;

    /**
     * Get the id value.
     *
     * @return the id value
     */
    public Integer id() {
        return this.id;
    }

    /**
     * Set the id value.
     *
     * @param id the id value to set
     * @return the MyTask object itself.
     */
    public MyTask withId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Get the title value.
     *
     * @return the title value
     */
    public String title() {
        return this.title;
    }

    /**
     * Set the title value.
     *
     * @param title the title value to set
     * @return the MyTask object itself.
     */
    public MyTask withTitle(String title) {
        this.title = title;
        return this;
    }

    /**
     * Get the description value.
     *
     * @return the description value
     */
    public String description() {
        return this.description;
    }

    /**
     * Set the description value.
     *
     * @param description the description value to set
     * @return the MyTask object itself.
     */
    public MyTask withDescription(String description) {
        this.description = description;
        return this;
    }

    /**
     * Get the isCompleted value.
     *
     * @return the isCompleted value
     */
    public Boolean isCompleted() {
        return this.isCompleted;
    }

    /**
     * Set the isCompleted value.
     *
     * @param isCompleted the isCompleted value to set
     * @return the MyTask object itself.
     */
    public MyTask withIsCompleted(Boolean isCompleted) {
        this.isCompleted = isCompleted;
        return this;
    }

    /**
     * Get the isHighPriority value.
     *
     * @return the isHighPriority value
     */
    public Boolean isHighPriority() {
        return this.isHighPriority;
    }

    /**
     * Set the isHighPriority value.
     *
     * @param isHighPriority the isHighPriority value to set
     * @return the MyTask object itself.
     */
    public MyTask withIsHighPriority(Boolean isHighPriority) {
        this.isHighPriority = isHighPriority;
        return this;
    }

}
